name: pagando_service
description: Pagando API Service
version: 0.1.0+3
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.22.2"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  retry: ^3.1.2
  flutter_image_compress: ^2.2.0
  get: ^4.6.6
  decimal: ^2.3.3
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
